# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY
  volumes:
    - name: m2-cache
      path: /root/.m2

steps:
  # 1) Instala FirmaElectronica.jar en el repositorio local de Maven
  - name: 'gcr.io/cloud-builders/mvn'
    volumes:
      - name: m2-cache
        path: /root/.m2
    args:
      - install:install-file
      - "-Dfile=libs/FirmaElectronica.jar"
      - "-DgroupId=com.aaamundial"
      - "-DartifactId=FirmaElectronica"
      - "-Dversion=1.0.0"
      - "-Dpackaging=jar"

  # 2) Empaqueta tu servicio (ahora encontrará FirmaElectronica en ~/.m2)
  - name: 'gcr.io/cloud-builders/mvn'
    volumes:
      - name: m2-cache
        path: /root/.m2
    args:
      - clean
      - package
      - -DskipTests

  # 3) Construye la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/firma-service:latest
      - .

  # 4) Sube la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - gcr.io/$PROJECT_ID/firma-service:latest

  # 5) Despliega en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - firma-service
      - --image=gcr.io/$PROJECT_ID/firma-service:latest
      - --region=southamerica-east1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=512Mi
      - --timeout=30s

# Declara el volumen al final
volumes:
  - name: m2-cache
    emptyDir: {}

# Opcional: lista de imágenes para notificación de build
images:
  - gcr.io/$PROJECT_ID/firma-service:latest
