steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: [
      'install:install-file',
      "-Dfile=libs/FirmaElectronica.jar",
      "-DgroupId=com.aaamundial",
      "-DartifactId=FirmaElectronica",
      "-Dversion=1.0.0",
      "-Dpackaging=jar"
    ]
  # 1) Empaquetar con Maven
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean','package','-DskipTests']
  # 2) Construir la imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build','-t','gcr.io/$PROJECT_ID/firma-service:latest','.'
    ]
  # 3) Subir imagen
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push','gcr.io/$PROJECT_ID/firma-service:latest'
    ]
  # 4) Desplegar en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run','deploy','firma-service',
      '--image','gcr.io/$PROJECT_ID/firma-service:latest',
      '--region','southamerica-east1',
      '--platform','managed',
      '--allow-unauthenticated',
      '--memory','512Mi',
      '--timeout','30s'
    ]
images:
  - 'gcr.io/$PROJECT_ID/firma-service:latest'
options:
  logging: CLOUD_LOGGING_ONLY
