# cloudbuild.yaml

steps:
  # 1) Instala FirmaElectronica.jar y empaqueta tu servicio en un solo comando
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package','-DskipTests']

  # 2) Construye la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - -t
      - "gcr.io/$PROJECT_ID/firma-service:latest"
      - .

  # 3) Sube la imagen a Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - push
      - "gcr.io/$PROJECT_ID/firma-service:latest"

  # 4) Despliega en Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - firma-service
      - --image=gcr.io/$PROJECT_ID/firma-service:latest
      - --region=southamerica-east1
      - --platform=managed
      - --allow-unauthenticated
      - --memory=512Mi
      - --timeout=30s

# Para notificar la imagen resultante
images:
  - "gcr.io/$PROJECT_ID/firma-service:latest"

# Opciones adicionales
options:
  logging: CLOUD_LOGGING_ONLY
